<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <PackageVersion>0.1.0</PackageVersion>
    <Authors>Niladri Prasad Padhy</Authors>
    <Company>Nuvyntra Labs</Company>
    <Copyright>Copyright (c) 2026 Niladri Prasad Padhy</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
